# Generated by Django 5.1.4 on 2025-01-06 23:17

import datetime
import django.contrib.auth.models
import django.db.models.deletion
import django_resized.forms
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Product Category',
            },
        ),
        migrations.CreateModel(
            name='CouponDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CouponName', models.CharField(max_length=69, verbose_name='Coupon Code')),
                ('Description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Coupon Description')),
                ('StartDate', models.DateTimeField(blank=True, null=True, verbose_name='When The Coupon Begins')),
                ('EndDate', models.DateTimeField(blank=True, null=True, verbose_name='When The Coupon Ends')),
                ('Discount', models.FloatField(blank=True, verbose_name='Discount Amount')),
                ('Promo_Code_Image', models.ImageField(blank=True, null=True, upload_to='Images/', verbose_name='Promo Code Picture')),
            ],
            options={
                'verbose_name_plural': 'Product Discount Coupon',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('Phone_Number', models.CharField(max_length=20)),
                ('Email_Address', models.EmailField(max_length=100)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShoppingDate', models.DateField(verbose_name='Date Customer Shopped')),
                ('ReviewScore', models.FloatField(verbose_name='Total Score out of 5')),
                ('TotalReview', models.TextField(blank=True, verbose_name='Customer Review')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSupportTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, verbose_name='Customer Email')),
                ('Inquiry', models.TextField(blank=True, verbose_name='Customer Technical Question(s)')),
                ('Answered', models.BooleanField(default=False, verbose_name='Has Support Ticket Been Answered')),
                ('Submission', models.DateTimeField(default=datetime.datetime(2025, 1, 6, 15, 17, 39, 539446))),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTestimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About', models.CharField(max_length=255, verbose_name='What the Testimonial is for')),
                ('First_Name', models.CharField(blank=True, max_length=255, verbose_name='First Name')),
                ('Testimonial', models.TextField(blank=True, verbose_name='The Entire Testimonial')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=255, verbose_name='First Name of Emergency Contact')),
                ('Last_Name', models.CharField(blank=True, max_length=255, verbose_name='Last Name of Emergency Contact')),
                ('Phone_Number', models.CharField(max_length=255, verbose_name='Phone Number of Emergency Contact')),
                ('Email_Address', models.EmailField(max_length=254, verbose_name='Email Address of Emergency Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='Full Job Description')),
                ('Salary', models.CharField(blank=True, max_length=255, null=True, verbose_name='Annual Salary For Job')),
                ('Location_Type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remote, Hybrid, or On-Site')),
                ('Filled', models.BooleanField(default=False, verbose_name='Has This Position Been Filled?')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Type', models.TextField(blank=True, max_length=255, verbose_name='The Category this FAQ Tech Question Falls Under')),
                ('Question', models.TextField(verbose_name='Technical Question')),
                ('Answer', models.TextField(blank=True, verbose_name='Technical Answer to the Technical Question')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=255, verbose_name="Applicant's First Name")),
                ('Last_Name', models.CharField(max_length=255, verbose_name="Applicant's Last Name")),
                ('DesiredJob', models.CharField(max_length=255, verbose_name="Applicant's Desired Job")),
                ('Phone_Number', models.CharField(max_length=255, verbose_name="Applicant's Phone Number")),
                ('Email_Address', models.EmailField(max_length=255, verbose_name="Applicant's Email Address")),
                ('Resume', models.FileField(blank=True, upload_to='', verbose_name="Applicant's Resume")),
                ('Cover_Letter', models.FileField(blank=True, upload_to='', verbose_name="Applicant's Cover Letter")),
                ('Submission', models.DateTimeField(default=datetime.datetime(2025, 1, 6, 15, 17, 39, 540559))),
            ],
        ),
        migrations.CreateModel(
            name='Key_Respons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job', models.CharField(blank=True, max_length=255, null=True, verbose_name='The Job This is For')),
                ('First', models.TextField(blank=True, max_length=255, null=True, verbose_name='1st Key Responsibility')),
                ('Second', models.TextField(blank=True, max_length=255, null=True, verbose_name='2nd Key Responsibility')),
                ('Third', models.TextField(blank=True, max_length=255, null=True, verbose_name='3rd Key Responsibility')),
                ('Fourth', models.TextField(blank=True, max_length=255, null=True, verbose_name='4th Key Responsibility')),
                ('Fifth', models.TextField(blank=True, max_length=255, null=True, verbose_name='5th Key Responsibility')),
                ('Sixth', models.TextField(blank=True, max_length=255, null=True, verbose_name='6th Key Responsibility')),
                ('Seventh', models.TextField(blank=True, max_length=255, null=True, verbose_name='7th Key Responsibility')),
                ('Eighth', models.TextField(blank=True, max_length=255, null=True, verbose_name='8th Key Responsibility')),
                ('Ninth', models.TextField(blank=True, max_length=255, null=True, verbose_name='9th Key Responsibility')),
                ('Tenth', models.TextField(blank=True, max_length=255, null=True, verbose_name='10th Key Responsibility')),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Name of the Image Being Used')),
                ('Image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[400, 400], upload_to='Images/', verbose_name='The Image')),
                ('Custom_File', models.FileField(blank=True, null=True, upload_to='', verbose_name='Any File')),
            ],
            options={
                'verbose_name_plural': 'Digital Images',
            },
        ),
        migrations.CreateModel(
            name='ReusableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Purpose of Data')),
                ('EEOS', models.TextField(blank=True, null=True, verbose_name='Equal Employment Opportunity Statement')),
                ('First_Benefit', models.TextField(blank=True, null=True, verbose_name='Job Benefits # 1')),
                ('Second_Benefit', models.TextField(blank=True, null=True, verbose_name='Job Benefits # 2')),
                ('Third_Benefit', models.TextField(blank=True, null=True, verbose_name='Job Benefits # 3')),
            ],
        ),
        migrations.CreateModel(
            name='StoreLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street', models.CharField(max_length=500, verbose_name='Location Street Address')),
                ('City', models.CharField(max_length=100, verbose_name='Location City')),
                ('State', models.CharField(max_length=20, verbose_name='Location State')),
                ('Zip', models.IntegerField(verbose_name='Location Zipcode Address')),
                ('Phone', models.CharField(max_length=20, verbose_name='Location Phone Number')),
                ('Opens', models.TimeField(verbose_name='When The Store Opens')),
                ('Closes', models.TimeField(verbose_name='When The Store Closes')),
                ('Store_Image', models.ImageField(blank=True, null=True, upload_to='Images/', verbose_name='Picture of the Computer Store')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shipping_First_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Shipping_Last_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Shipping_Email', models.CharField(blank=True, max_length=255, null=True)),
                ('Shipping_Address_Line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('Shipping_Address_Line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('Shipping_City', models.CharField(blank=True, max_length=255, null=True)),
                ('Shipping_State', models.CharField(blank=True, max_length=255, null=True)),
                ('Shipping_ZipCode', models.CharField(blank=True, max_length=255, null=True)),
                ('Shipping_Country', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Shipping',
            },
        ),
        migrations.CreateModel(
            name='CurrentEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=255, verbose_name='First Name of Employee')),
                ('Last_Name', models.CharField(blank=True, max_length=255, verbose_name='Last Name of Employee')),
                ('Date_Of_Birth', models.DateField(blank=True, verbose_name="Employee's Birthday")),
                ('Social_Security', models.CharField(blank=True, max_length=255, verbose_name='Social Security Number')),
                ('Street_Address', models.CharField(blank=True, max_length=255, verbose_name='Street Address of Employee')),
                ('City_Address', models.CharField(blank=True, max_length=255, verbose_name='City Address of Employee')),
                ('State_Address', models.CharField(blank=True, max_length=255, verbose_name='State Address of Employee')),
                ('Zipcode_Address', models.CharField(blank=True, max_length=255, verbose_name='Zipcode Address of Employee')),
                ('W2_Tax_Information', models.FileField(blank=True, upload_to='', verbose_name="Employee's W2 Form")),
                ('Employment_Contract', models.FileField(blank=True, upload_to='', verbose_name='Current Work Contract for Employee')),
                ('Emergency_Contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.emergencycontact')),
                ('Job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.employment')),
            ],
        ),
        migrations.AddField(
            model_name='employment',
            name='Key_Responsibilities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.key_respons'),
        ),
        migrations.CreateModel(
            name='Online_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=255, null=True)),
                ('Full_Address', models.TextField(blank=True, max_length=255, null=True)),
                ('Total_Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('Shipment_Released', models.BooleanField(default=False, verbose_name='Has the Order Shipped?')),
                ('Shipment', models.DateTimeField(default=datetime.datetime(2025, 1, 6, 15, 17, 39, 538581), verbose_name='Order Shipment Date')),
                ('Invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('Paid', models.BooleanField(default=False, verbose_name='Has the Order Been Paid?')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Online Customer Orders',
            },
        ),
        migrations.AddField(
            model_name='employment',
            name='EEOS_And_Benefits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.reusabledata'),
        ),
        migrations.AddField(
            model_name='employment',
            name='Store_Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.storelocations'),
        ),
        migrations.CreateModel(
            name='StoreProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('Brand', models.CharField(blank=True, max_length=999, null=True, verbose_name='Product Brand')),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Selling Price')),
                ('On_Sale', models.BooleanField(default=False, verbose_name='Is product on Sale?')),
                ('Sale_Price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='On Sale Price')),
                ('SKU', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product SKU')),
                ('UPC', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product UPC')),
                ('Serial', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Serial Number')),
                ('Stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Product Stock')),
                ('Summary', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Product Summary')),
                ('Key_Feat_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 1')),
                ('Key_Feat_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 2')),
                ('Key_Feat_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 3')),
                ('Key_Feat_4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 4')),
                ('Key_Feat_5', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 5')),
                ('Key_Feat_6', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 6')),
                ('Key_Feat_7', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 7')),
                ('Key_Feat_8', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 8')),
                ('Key_Feat_9', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 9')),
                ('Key_Feat_10', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 10')),
                ('Picture', models.ImageField(blank=True, null=True, upload_to='Images/', verbose_name='Product Picture')),
                ('Spec_Sheet', models.ImageField(blank=True, null=True, upload_to='Images/', verbose_name='Specification Sheet')),
                ('Discontinued', models.BooleanField(default=False, verbose_name='EOL Product')),
                ('Category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Website.category')),
                ('Coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.coupondiscount')),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Orderable_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveBigIntegerField(default=1)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('OrderID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.online_orders')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.storeproducts')),
            ],
            options={
                'verbose_name_plural': 'Orderable Products',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Number', models.CharField(default=uuid.uuid4, max_length=255, verbose_name='Unique Order Number')),
                ('Quantity', models.IntegerField(default=1)),
                ('Address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address to Ship the Order to')),
                ('Email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Order Reciever`s Contact Email Address')),
                ('Phone', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Order Reciever`s Contact Phone Number')),
                ('Date', models.DateField(default=datetime.datetime.today, verbose_name='Date of Placing the Order')),
                ('Status', models.BooleanField(default=False, verbose_name='Has Order Been Shipped?')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.customer')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.storeproducts')),
            ],
            options={
                'verbose_name_plural': 'Customer Orders',
            },
        ),
        migrations.CreateModel(
            name='WebsiteAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modify_Date', models.DateTimeField(auto_now_add=True, verbose_name=django.contrib.auth.models.User)),
                ('Phone_Number', models.CharField(blank=True, max_length=50, verbose_name='Account`s Phone Number')),
                ('Address1', models.CharField(blank=True, max_length=50, verbose_name='Account`s Address Line 1')),
                ('Address2', models.CharField(blank=True, max_length=50, verbose_name='Account`s Address Line 2')),
                ('City', models.CharField(blank=True, max_length=50, verbose_name='Account`s Adress City')),
                ('State', models.CharField(blank=True, max_length=50, verbose_name='Account`s Adress State')),
                ('ZipCode', models.CharField(blank=True, max_length=50, verbose_name='Account`s Adress Zipcode')),
                ('Country', models.CharField(blank=True, max_length=50, verbose_name='Account`s Adress Country')),
                ('Old_Cart', models.CharField(blank=True, max_length=200, verbose_name='Old Shopping Cart Key Value Pair')),
                ('Web_User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Online Website Accounts',
            },
        ),
    ]
