# Generated by Django 4.1.7 on 2023-11-01 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CouponName', models.CharField(max_length=69, verbose_name='Coupon Code')),
                ('Description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Coupon Description')),
                ('StartDate', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('EndDate', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('Discount', models.FloatField(blank=True, verbose_name='Discount Amount')),
                ('Promo_Code_Image', models.ImageField(blank=True, null=True, upload_to='Images/', verbose_name='Promo Code Picture')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShoppingDate', models.DateField(verbose_name='Date Customer Shopped')),
                ('ReviewScore', models.FloatField(verbose_name='Total Score out of 5')),
                ('TotalReview', models.TextField(blank=True, verbose_name='Customer Review')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSupportTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, verbose_name='Customer Email')),
                ('Inquiry', models.TextField(blank=True, verbose_name='Customer Technical Question(s)')),
                ('Answered', models.BooleanField(default=False, verbose_name='Has Support Ticket Been Answered')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTestimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About', models.CharField(max_length=255, verbose_name='What the Testimonial is for')),
                ('First_Name', models.CharField(blank=True, max_length=255, verbose_name='First Name')),
                ('Testimonial', models.TextField(blank=True, verbose_name='The Entire Testimonial')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=255, verbose_name='First Name of Emergency Contact')),
                ('Last_Name', models.CharField(blank=True, max_length=255, verbose_name='Last Name of Emergency Contact')),
                ('Phone_Number', models.CharField(max_length=255, verbose_name='Phone Number of Emergency Contact')),
                ('Email_Address', models.EmailField(max_length=254, verbose_name='Email Address of Emergency Contact')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Type', models.TextField(blank=True, max_length=255, verbose_name='The Category this FAQ Tech Question Falls Under')),
                ('Question', models.TextField(verbose_name='Technical Question')),
                ('Answer', models.TextField(blank=True, verbose_name='Technical Answer to the Technical Question')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=255, verbose_name="Applicant's First Name")),
                ('Last_Name', models.CharField(max_length=255, verbose_name="Applicant's Last Name")),
                ('DesiredJob', models.CharField(max_length=255, verbose_name="Applicant's Desired Job")),
                ('Phone_Number', models.CharField(max_length=255, verbose_name="Applicant's Phone Number")),
                ('Email_Address', models.EmailField(max_length=255, verbose_name="Applicant's Email Address")),
                ('Resume', models.FileField(blank=True, upload_to='', verbose_name="Applicant's Resume")),
                ('Cover_Letter', models.FileField(blank=True, upload_to='', verbose_name="Applicant's Cover Letter")),
            ],
        ),
        migrations.CreateModel(
            name='Key_Respons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job', models.CharField(blank=True, max_length=255, null=True, verbose_name='The Job This is For')),
                ('First', models.TextField(blank=True, max_length=255, null=True, verbose_name='1st Key Responsibility')),
                ('Second', models.TextField(blank=True, max_length=255, null=True, verbose_name='2nd Key Responsibility')),
                ('Third', models.TextField(blank=True, max_length=255, null=True, verbose_name='3rd Key Responsibility')),
                ('Fourth', models.TextField(blank=True, max_length=255, null=True, verbose_name='4th Key Responsibility')),
                ('Fifth', models.TextField(blank=True, max_length=255, null=True, verbose_name='5th Key Responsibility')),
                ('Sixth', models.TextField(blank=True, max_length=255, null=True, verbose_name='6th Key Responsibility')),
                ('Seventh', models.TextField(blank=True, max_length=255, null=True, verbose_name='7th Key Responsibility')),
                ('Eighth', models.TextField(blank=True, max_length=255, null=True, verbose_name='8th Key Responsibility')),
                ('Ninth', models.TextField(blank=True, max_length=255, null=True, verbose_name='9th Key Responsibility')),
                ('Tenth', models.TextField(blank=True, max_length=255, null=True, verbose_name='10th Key Responsibility')),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Name of the Image Being Used')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Images/', verbose_name='The Image')),
                ('Custom_File', models.FileField(blank=True, null=True, upload_to='', verbose_name='Any File')),
            ],
        ),
        migrations.CreateModel(
            name='ReusableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Purpose of Data')),
                ('EEOS', models.TextField(blank=True, null=True, verbose_name='Equal Employment Opportunity Statement')),
                ('First_Benefit', models.TextField(blank=True, null=True, verbose_name='Job Benefits # 1')),
                ('Second_Benefit', models.TextField(blank=True, null=True, verbose_name='Job Benefits # 2')),
                ('Third_Benefit', models.TextField(blank=True, null=True, verbose_name='Job Benefits # 3')),
            ],
        ),
        migrations.CreateModel(
            name='StoreLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street', models.CharField(max_length=500, verbose_name='Location Street Address')),
                ('City', models.CharField(max_length=100, verbose_name='Location City')),
                ('State', models.CharField(max_length=20, verbose_name='Location State')),
                ('Zip', models.IntegerField(verbose_name='Location Zipcode Address')),
                ('Phone', models.CharField(max_length=20, verbose_name='Location Phone Number')),
                ('Opens', models.TimeField(verbose_name='Opening Time')),
                ('Closes', models.TimeField(verbose_name='Closing Time')),
                ('Store_Image', models.ImageField(blank=True, null=True, upload_to='Images/', verbose_name='Picture of the Computer Store')),
            ],
        ),
        migrations.CreateModel(
            name='TEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TESt', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StoreProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('Brand', models.CharField(blank=True, max_length=999, null=True, verbose_name='Product Brand')),
                ('Price', models.FloatField(verbose_name='Product Price')),
                ('SKU', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product SKU')),
                ('UPC', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product UPC')),
                ('Stock', models.IntegerField(blank=True, null=True, verbose_name='Product Stock')),
                ('Summary', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Product Summary')),
                ('Key_Feat_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 1')),
                ('Key_Feat_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 2')),
                ('Key_Feat_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 3')),
                ('Key_Feat_4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 4')),
                ('Key_Feat_5', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 5')),
                ('Key_Feat_6', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 6')),
                ('Key_Feat_7', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 7')),
                ('Key_Feat_8', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 8')),
                ('Key_Feat_9', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 9')),
                ('Key_Feat_10', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Prod Feat # 10')),
                ('Picture', models.ImageField(blank=True, null=True, upload_to='Images/', verbose_name='Product Picture')),
                ('Category', models.TextField(blank=True, null=True, verbose_name="Product Classification's for Organization")),
                ('Discontinued', models.BooleanField(default=False, verbose_name='EOL Product')),
                ('Coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.coupondiscount')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='Full Job Description')),
                ('Salary', models.CharField(blank=True, max_length=255, null=True, verbose_name='Annual Salary For Job')),
                ('Location_Type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remote, Hybrid, or On-Site')),
                ('Filled', models.BooleanField(default=False, verbose_name='Has This Position Been Filled?')),
                ('EEOS_And_Benefits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.reusabledata')),
                ('Key_Responsibilities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.key_respons')),
                ('Store_Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.storelocations')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=255, verbose_name='First Name of Employee')),
                ('Last_Name', models.CharField(blank=True, max_length=255, verbose_name='Last Name of Employee')),
                ('Date_Of_Birth', models.DateField(blank=True, verbose_name="Employee's Birthday")),
                ('Social_Security', models.CharField(blank=True, max_length=255, verbose_name='Social Security Number')),
                ('Street_Address', models.CharField(blank=True, max_length=255, verbose_name='Street Address of Employee')),
                ('City_Address', models.CharField(blank=True, max_length=255, verbose_name='City Address of Employee')),
                ('State_Address', models.CharField(blank=True, max_length=255, verbose_name='State Address of Employee')),
                ('Zipcode_Address', models.CharField(blank=True, max_length=255, verbose_name='Zipcode Address of Employee')),
                ('W2_Tax_Information', models.FileField(blank=True, upload_to='', verbose_name="Employee's W2 Form")),
                ('Employment_Contract', models.FileField(blank=True, upload_to='', verbose_name='Current Work Contract for Employee')),
                ('Emergency_Contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.emergencycontact')),
                ('Job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.employment')),
            ],
        ),
    ]
