# Generated by Django 5.1.4 on 2025-01-06 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupporttickets',
            name='Submission',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 15, 18, 31, 295176)),
        ),
        migrations.AlterField(
            model_name='jobapplications',
            name='Submission',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 15, 18, 31, 296309)),
        ),
        migrations.AlterField(
            model_name='online_orders',
            name='Shipment',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 15, 18, 31, 294325), verbose_name='Order Shipment Date'),
        ),
    ]
