# Generated by Django 4.2.7 on 2024-11-26 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteaccounts',
            name='Old_Cart',
            field=models.CharField(blank=True, max_length=200, verbose_name='Old Shopping Cart Key Value Pair'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customersupporttickets',
            name='Submission',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 23, 36, 40, 454972)),
        ),
        migrations.AlterField(
            model_name='jobapplications',
            name='Submission',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 23, 36, 40, 456980)),
        ),
        migrations.AlterField(
            model_name='online_orders',
            name='Shipment',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 23, 36, 40, 453466)),
        ),
    ]
