# Generated by Django 4.2.7 on 2024-11-26 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_websiteaccounts_old_cart_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupporttickets',
            name='Submission',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 26, 0, 52, 43, 62452)),
        ),
        migrations.AlterField(
            model_name='jobapplications',
            name='Submission',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 26, 0, 52, 43, 63962)),
        ),
        migrations.AlterField(
            model_name='online_orders',
            name='Shipment',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 26, 0, 52, 43, 61453)),
        ),
    ]
